-- Create affiliate_stats table
CREATE TABLE affiliate_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  campaign_code TEXT NOT NULL,
  deposit DECIMAL(18,9) NOT NULL DEFAULT 0,
  lifetime_wagered DECIMAL(18,9) NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create index on username and campaign_code
CREATE INDEX idx_affiliate_stats_username ON affiliate_stats(username);
CREATE INDEX idx_affiliate_stats_campaign ON affiliate_stats(campaign_code);

-- Create a function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create a trigger to automatically update updated_at
CREATE TRIGGER update_affiliate_stats_updated_at
    BEFORE UPDATE ON affiliate_stats
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column(); 