name: Leaderboard Automation

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly Update
        run: |
          curl -X POST "https://archslots.vercel.app/api/cron/hourly-update" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET_KEY }}"
        if: github.event_name == 'schedule'

      - name: Weekly Reset
        run: |
          curl -X POST "https://archslots.vercel.app/api/cron/weekly-reset" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET_KEY }}"
        if: github.event_name == 'workflow_dispatch' 